[workspace]
resolver = "2"
members = ["net","snow"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
bytes = "1.11.0"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
