[workspace]
resolver = "2"
members = ["net", "server", "snow"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
bytes = "1.11.0"
rand = "0.9.2"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
