name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches-ignore: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Checks (Fmt, Clippy)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain and Components
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Format Check
        run: cargo fmt --check

      - name: Lint (Clippy)
        run: cargo clippy -- -D warnings

  security_audit:
    name: Security & Coverage
    runs-on: ubuntu-latest
    needs: [check]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Install cargo-audit
        run: cargo install cargo-audit --version 0.22.0

      - name: Install cargo-deny
        run: cargo install cargo-deny --version 0.18.8
        
      - name: Security Check
        run: cargo audit

      - name: Dependency policy check
        run: cargo deny check

  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: [security_audit]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Build and Test
        run: cargo test --verbose
        
      - name: Install cargo-chef
        run: cargo install cargo-chef
        
      - name: Build using cargo chef
        run: |
          cargo chef prepare --recipe-path recipe.json
          cargo chef cook --recipe-path recipe.json
          cargo build --release