[package]
name = "net"
version = "0.1.0"
edition.workspace = true
description = "A raknet implementation in Rust for Snow Software"

[dependencies]
error = { path = "../error" }

bytes.workspace = true
rand.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
